import AppKit
import Testing
@testable import sarari

/// クリップボードに立てる目印（Issue #79 / #105）。
///
/// `NSPasteboard.general` は触らず、テスト専用の名前付きペーストボードで
/// **同じ組み立て方**を再現して検証する（`TextInjector.write` は private かつ general 固定）。
@MainActor
struct PasteboardMarkerTests {

    private func withPasteboard(_ body: (NSPasteboard) -> Void) {
        let pb = NSPasteboard(name: NSPasteboard.Name("sarari.tests.\(UUID().uuidString)"))
        defer { pb.releaseGlobally() }
        pb.clearContents()
        body(pb)
    }

    /// 挿入用の組み立て。`TextInjector.write(_:purpose: .injection)` と同じ 4 つを立てる。
    private func writeInjection(_ text: String, to pb: NSPasteboard) {
        pb.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: PasteboardPrivacy.concealed)
        item.setString("", forType: PasteboardPrivacy.transient)
        item.setString("", forType: PasteboardPrivacy.autoGenerated)
        item.setString(PasteboardPrivacy.sourceValue, forType: PasteboardPrivacy.source)
        pb.writeObjects([item])
    }

    /// nspasteboard.org の取り決め。**型名を間違えるとマネージャは黙って無視する**ので、
    /// 綴りをここで固定する（テストが唯一の検査手段）。
    @Test("目印の型名が取り決めどおり")
    func markerNames() {
        #expect(PasteboardPrivacy.concealed.rawValue == "org.nspasteboard.ConcealedType")
        #expect(PasteboardPrivacy.transient.rawValue == "org.nspasteboard.TransientType")
        #expect(PasteboardPrivacy.autoGenerated.rawValue == "org.nspasteboard.AutoGeneratedType")
        #expect(PasteboardPrivacy.source.rawValue == "org.nspasteboard.source")
    }

    @Test("source は自分の bundle ID（取れなければ sarari）")
    func sourceIsOwnBundleId() {
        #expect(!PasteboardPrivacy.sourceValue.isEmpty)
    }

    /// `Concealed` だけだと「記録はするが伏字」のマネージャに残る。**残さないことが目的**なので
    /// `Transient`（履歴に記録しない）と `AutoGenerated`（ユーザーの Copy ではない）が要る。
    @Test("挿入用は 4 つとも立ち、本文も読める")
    func injectionSetsEveryMarker() {
        withPasteboard { pb in
            writeInjection("口述テキスト", to: pb)
            let types = pb.types ?? []
            #expect(types.contains(PasteboardPrivacy.concealed))
            #expect(types.contains(PasteboardPrivacy.transient))
            #expect(types.contains(PasteboardPrivacy.autoGenerated))
            #expect(pb.string(forType: PasteboardPrivacy.source) == PasteboardPrivacy.sourceValue)
            // 目印を足しても ⌘V で貼る本文は普通に読めること。
            #expect(pb.string(forType: .string) == "口述テキスト")
        }
    }

    /// ユーザーが「コピー」を押したものまで履歴から消すと、「さっきコピーしたのに無い」になる。
    @Test("ユーザーのコピーは Concealed だけで、Transient を立てない")
    func userCopyKeepsHistory() {
        withPasteboard { pb in
            let item = NSPasteboardItem()
            item.setString("手でコピーした文", forType: .string)
            item.setString("", forType: PasteboardPrivacy.concealed)
            pb.writeObjects([item])

            let types = pb.types ?? []
            #expect(types.contains(PasteboardPrivacy.concealed))
            #expect(!types.contains(PasteboardPrivacy.transient))
            #expect(!types.contains(PasteboardPrivacy.autoGenerated))
        }
    }
}
