import AppKit
import Testing
@testable import sarari

/// クリップボードの機密マーカーと、全 type の退避／復元（Issue #79）。
/// `NSPasteboard.general` は触らず、テスト専用の名前付きペーストボードを使う。
/// 名前付きペーストボードはプロセスではなくログインセッションの pboard サーバーに残るので、
/// 使い終わったら `releaseGlobally()` で必ず解放する（`withPasteboard` が面倒を見る）。
@MainActor
struct PasteboardTests {

    private func withPasteboard(_ body: (NSPasteboard) -> Void) {
        let pb = NSPasteboard(name: NSPasteboard.Name("sarari.tests.\(UUID().uuidString)"))
        defer { pb.releaseGlobally() }
        pb.clearContents()
        body(pb)
    }

    /// 読む側の判定（`isReadable`）は #130 で消えた（クリップボードを読む唯一の消費者だった
    /// コンテキスト注入ごと削除したため）。**書く側のマーカーは #105 で使うので生きている。**
    @Test("機密マーカーの type 名が nspasteboard.org の取り決めどおり")
    func markerNames() {
        #expect(PasteboardPrivacy.concealed.rawValue == "org.nspasteboard.ConcealedType")
        #expect(PasteboardPrivacy.transient.rawValue == "org.nspasteboard.TransientType")
        #expect(PasteboardPrivacy.autoGenerated.rawValue == "org.nspasteboard.AutoGeneratedType")
    }

    @Test("スナップショットは全 type を退避し、書き潰したあとに戻せる")
    func snapshotRestoresAllTypes() {
        withPasteboard { pb in
            let item = NSPasteboardItem()
            item.setString("本文", forType: .string)
            item.setData(Data([0x01, 0x02]), forType: .tiff)
            pb.writeObjects([item])

            let snapshot = PasteboardSnapshot.capture(pb)
            #expect(!snapshot.isEmpty)

            pb.clearContents()
            pb.setString("口述テキスト", forType: .string)
            #expect(pb.string(forType: .string) == "口述テキスト")

            snapshot.restore(to: pb)
            #expect(pb.string(forType: .string) == "本文")
            #expect(pb.data(forType: .tiff) == Data([0x01, 0x02]))
        }
    }

    @Test("空のスナップショットは復元で何もしない（復元のつもりで消さない）")
    func emptySnapshotIsNoop() {
        withPasteboard { pb in
            let snapshot = PasteboardSnapshot.capture(pb)
            #expect(snapshot.isEmpty)

            pb.setString("残すべき内容", forType: .string)
            snapshot.restore(to: pb)
            #expect(pb.string(forType: .string) == "残すべき内容")
        }
    }
}
