import AppKit

/// クリップボードの「機密」の目印。
///
/// パスワードマネージャ（1Password / Bitwarden / キーチェーンアクセス等）は慣習的に
/// `org.nspasteboard.ConcealedType` を立て、一時的な内容には `TransientType` /
/// `AutoGeneratedType` を立てる。標準 API ではないが、クリップボードマネージャと
/// パスワードマネージャの間で広く守られている取り決め（nspasteboard.org）。
///
/// **書く側**がこれを立てないと、口述したテキストが Maccy / Raycast / Paste のような
/// 常駐クリップボードマネージャの DB に永久保存される（Issue #79）。
///
/// 読む側の判定（`isReadable`）も持っていたが、クリップボードを読む唯一の消費者だった
/// コンテキスト注入を外した（#130）ので一緒に落とした。`transient` / `autoGenerated` は
/// 書き込みに付ける #105 で使う。
enum PasteboardPrivacy {
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// 誰が置いたか。クリップボードマネージャが「どのアプリの一時データか」を判別する。
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// 自分が置いたことを示す値。
    static var sourceValue: String { Bundle.main.bundleIdentifier ?? "sarari" }
}

/// クリップボードの中身をそのまま戻すためのスナップショット。
///
/// `string(forType: .string)` だけを退避すると、**プレーンテキスト以外は復元できない**。
/// スクショを撮った直後（クリップボードは画像）に口述すると、復元処理は
/// `previous == nil` なので `clearContents()` だけを実行し、**クリップボードが空になる**。
/// Finder のファイルコピー、Excel のセル範囲、書式付きテキストでも同じことが起きる。
/// 元データは挿入時の `clearContents()` で既に消えているので、ここが唯一の救済（Issue #79）。
struct PasteboardSnapshot {
    /// アイテムごとの、type → データ。
    private let items: [[NSPasteboard.PasteboardType: Data]]

    var isEmpty: Bool { items.allSatisfy(\.isEmpty) }

    @MainActor
    static func capture(_ pasteboard: NSPasteboard) -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            var stored: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                // ファイルプロミスなど、データとして取り出せない type は諦める
                // （それでもプレーンテキストだけを持つ従来より確実に広い）。
                if let data = item.data(forType: type) { stored[type] = data }
            }
            return stored
        }
        return PasteboardSnapshot(items: items)
    }

    /// 退避した内容を書き戻す。空のスナップショットなら**何もしない**
    /// （空で上書きすると、復元のつもりでクリップボードを消すことになる）。
    @MainActor
    func restore(to pasteboard: NSPasteboard) {
        guard !isEmpty else { return }
        let restored = items.compactMap { stored -> NSPasteboardItem? in
            guard !stored.isEmpty else { return nil }
            let item = NSPasteboardItem()
            for (type, data) in stored { item.setData(data, forType: type) }
            return item
        }
        guard !restored.isEmpty else { return }
        pasteboard.clearContents()
        pasteboard.writeObjects(restored)
    }
}
